[project]
name = "wm-summer-school"
version = "2025.04"
description = "Database preparation workflow for the W&M Summer School"
requires-python = "==3.11.*"
dependencies = [
    "disruption-py==0.11.0",
]

